# Generated by Django 5.0.2 on 2025-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calendar_app', '0005_alter_daymenu_options_alter_foodcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_admin'], name='calendar_ap_is_admi_e7b497_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='calendar_ap_usernam_e86ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='daymenu',
            index=models.Index(fields=['date'], name='calendar_ap_date_2d14cb_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['name'], name='calendar_ap_name_1b87b0_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['category', 'name'], name='calendar_ap_categor_033c00_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['is_complete_dish'], name='calendar_ap_is_comp_b489c6_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['excel_row'], name='calendar_ap_excel_r_b28ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='userselection',
            index=models.Index(fields=['user', 'day_menu'], name='calendar_ap_user_id_d60016_idx'),
        ),
        migrations.AddIndex(
            model_name='userselection',
            index=models.Index(fields=['day_menu'], name='calendar_ap_day_men_b30dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='userselection',
            index=models.Index(fields=['user'], name='calendar_ap_user_id_27432c_idx'),
        ),
        migrations.AddIndex(
            model_name='userselection',
            index=models.Index(fields=['not_eating'], name='calendar_ap_not_eat_973614_idx'),
        ),
    ]
